import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eef7f5',
          100: '#d7ebe7',
          200: '#b7d7d1',
          300: '#8fc0b8',
          400: '#629f97',
          500: '#3f7f78',
          600: '#2f6963',
          700: '#25544f',
          800: '#1f4541',
          900: '#1b3936',
          950: '#0f2221',
        },
        accent: {
          50: '#fcf5f2',
          100: '#f6e3da',
          200: '#eec5b2',
          300: '#e09a79',
          400: '#cf6b47',
          500: '#bb4a2a',
          600: '#9e3b22',
          700: '#7f311d',
          800: '#672a1b',
          900: '#552416',
          950: '#2f120b',
        },
        neutral: {
          50: '#fbf8f1',
          100: '#f3eee4',
          200: '#e7decf',
          300: '#d7cab5',
          400: '#b8a78f',
          500: '#8f7d67',
          600: '#6c5d4c',
          700: '#4c4136',
          800: '#332c26',
          850: '#26211d',
          900: '#1d1916',
          950: '#120f0d',
        },
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'Helvetica Neue', 'Arial', 'sans-serif'],
        serif: ['Source Serif 4', 'Georgia', 'Cambria', 'Times New Roman', 'serif'],
        display: ['Fraunces', 'Source Serif 4', 'Georgia', 'serif'],
        mono: ['IBM Plex Mono', 'SFMono-Regular', 'Menlo', 'Monaco', 'monospace'],
      },
      fontSize: {
        hero: ['clamp(4rem, 9vw, 8rem)', { lineHeight: '0.92', letterSpacing: '-0.04em', fontWeight: '600' }],
        display: ['clamp(2.9rem, 6vw, 5.5rem)', { lineHeight: '0.96', letterSpacing: '-0.03em', fontWeight: '600' }],
        heading: ['clamp(1.65rem, 3vw, 2.35rem)', { lineHeight: '1.08', letterSpacing: '-0.02em', fontWeight: '600' }],
        kicker: ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.28em', fontWeight: '600' }],
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
        26: '6.5rem',
        30: '7.5rem',
      },
      typography: ({ theme }: { theme: (path: string) => string }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.neutral.700'),
            '--tw-prose-headings': theme('colors.neutral.900'),
            '--tw-prose-lead': theme('colors.neutral.600'),
            '--tw-prose-links': theme('colors.primary.700'),
            '--tw-prose-bold': theme('colors.neutral.900'),
            '--tw-prose-counters': theme('colors.neutral.500'),
            '--tw-prose-bullets': theme('colors.neutral.400'),
            '--tw-prose-hr': theme('colors.neutral.300'),
            '--tw-prose-quotes': theme('colors.neutral.700'),
            '--tw-prose-quote-borders': theme('colors.accent.300'),
            '--tw-prose-captions': theme('colors.neutral.500'),
            '--tw-prose-code': theme('colors.accent.700'),
            '--tw-prose-pre-code': theme('colors.neutral.100'),
            '--tw-prose-pre-bg': theme('colors.neutral.950'),
            '--tw-prose-th-borders': theme('colors.neutral.300'),
            '--tw-prose-td-borders': theme('colors.neutral.200'),
            fontFamily: theme('fontFamily.serif').join(', '),
            fontSize: '1.15rem',
            lineHeight: '1.9',
            maxWidth: 'none',
            p: {
              marginTop: '1.15em',
              marginBottom: '1.15em',
            },
            h1: {
              fontFamily: theme('fontFamily.display').join(', '),
              fontWeight: '600',
              fontSize: 'clamp(2.85rem, 6vw, 4.75rem)',
              lineHeight: '0.96',
              letterSpacing: '-0.035em',
              marginTop: '0',
              marginBottom: '0.5em',
            },
            h2: {
              fontFamily: theme('fontFamily.display').join(', '),
              fontWeight: '550',
              fontSize: 'clamp(2rem, 4vw, 2.8rem)',
              lineHeight: '1.02',
              letterSpacing: '-0.03em',
              marginTop: '2.2em',
              marginBottom: '0.6em',
            },
            h3: {
              fontFamily: theme('fontFamily.sans').join(', '),
              fontWeight: '600',
              fontSize: '1.1rem',
              letterSpacing: '0.08em',
              textTransform: 'uppercase',
              marginTop: '2.4em',
              marginBottom: '0.5em',
            },
            h4: {
              fontFamily: theme('fontFamily.sans').join(', '),
              fontWeight: '600',
              letterSpacing: '0.05em',
              textTransform: 'uppercase',
              fontSize: '0.95rem',
              marginTop: '2em',
              marginBottom: '0.5em',
            },
            strong: {
              fontWeight: '600',
            },
            code: {
              fontFamily: theme('fontFamily.mono').join(', '),
              fontWeight: '500',
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            pre: {
              fontFamily: theme('fontFamily.mono').join(', '),
              borderRadius: '1rem',
              padding: '1.25rem 1.5rem',
            },
            blockquote: {
              borderLeftWidth: '1px',
              paddingLeft: '1.4rem',
              fontStyle: 'normal',
              fontWeight: '400',
              color: theme('colors.neutral.600'),
              marginTop: '2em',
              marginBottom: '2em',
            },
            'blockquote p:first-of-type::before': {
              content: 'none',
            },
            a: {
              textDecoration: 'underline',
              textDecorationColor: theme('colors.primary.300'),
              textUnderlineOffset: '0.18em',
              textDecorationThickness: '1px',
            },
            'a:hover': {
              textDecorationColor: theme('colors.primary.600'),
            },
            hr: {
              marginTop: '3em',
              marginBottom: '3em',
            },
            ul: {
              marginTop: '1.25em',
              marginBottom: '1.25em',
            },
            ol: {
              marginTop: '1.25em',
              marginBottom: '1.25em',
            },
            li: {
              marginTop: '0.5em',
              marginBottom: '0.5em',
            },
          },
        },
        dark: {
          css: {
            '--tw-prose-body': theme('colors.neutral.300'),
            '--tw-prose-headings': theme('colors.neutral.100'),
            '--tw-prose-lead': theme('colors.neutral.400'),
            '--tw-prose-links': theme('colors.primary.300'),
            '--tw-prose-bold': theme('colors.neutral.100'),
            '--tw-prose-counters': theme('colors.neutral.400'),
            '--tw-prose-bullets': theme('colors.neutral.600'),
            '--tw-prose-hr': theme('colors.neutral.700'),
            '--tw-prose-quotes': theme('colors.neutral.300'),
            '--tw-prose-quote-borders': theme('colors.accent.500'),
            '--tw-prose-captions': theme('colors.neutral.400'),
            '--tw-prose-code': theme('colors.accent.200'),
            '--tw-prose-pre-code': theme('colors.neutral.200'),
            '--tw-prose-pre-bg': theme('colors.neutral.850'),
            '--tw-prose-th-borders': theme('colors.neutral.600'),
            '--tw-prose-td-borders': theme('colors.neutral.700'),
          },
        },
      }),
      animation: {
        'fade-up': 'fadeUp 0.7s cubic-bezier(0.2, 1, 0.32, 1) forwards',
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'slide-in': 'slideIn 0.45s cubic-bezier(0.2, 1, 0.32, 1) forwards',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(-10px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};

export default config;